import { useCallback } from "react";
import { useSharedBundleHandlers } from "../../../hooks/useSharedBundleHandlers";
import { usePpbBaseConfigureState } from "./usePpbBaseConfigureState";
import { usePpbVisibilityState } from "./usePpbVisibilityState";
import { usePpbDisplayOptionsState } from "./usePpbDisplayOptionsState";
import { usePpbBundleSettingsState } from "./usePpbBundleSettingsState";
import { usePpbTemplateUiState } from "./usePpbTemplateUiState";
import { usePpbMultiLanguageHandlers } from "./usePpbMultiLanguageHandlers";
import { usePpbCategoryHandlers } from "./usePpbCategoryHandlers";
import { usePpbSaveHandlers } from "./usePpbSaveHandlers";
import { usePpbFetcherEffects } from "./usePpbFetcherEffects";
import { usePpbPreviewReadinessHandlers } from "./usePpbPreviewReadinessHandlers";
import { usePpbPlacementHandlers } from "./usePpbPlacementHandlers";
import { usePpbModalAndTemplateController } from "./usePpbModalAndTemplateController";

export function usePpbConfigureFlow() {
  const base = usePpbBaseConfigureState();
  const visibility = usePpbVisibilityState({
    bundle: base.bundle,
  });
  const display = usePpbDisplayOptionsState({
    bundle: base.bundle,
    shopLocales: base.shopLocales,
    pricingState: base.pricingState,
    markAsDirty: base.markAsDirty,
  });
  const settings = usePpbBundleSettingsState({ bundle: base.bundle });
  const templateState = usePpbTemplateUiState({ bundle: base.bundle });
  const multiLanguage = usePpbMultiLanguageHandlers({
    shopLocales: base.shopLocales,
    stepsState: base.stepsState,
    textOverridesByLocale: base.textOverridesByLocale,
    setTextOverridesByLocale: base.setTextOverridesByLocale,
    bundleEmbedMultiLangText: visibility.bundleEmbedMultiLangText,
    setBundleEmbedMultiLangText: visibility.setBundleEmbedMultiLangText,
    bundleWidgetMultiLangText: visibility.bundleWidgetMultiLangText,
    setBundleWidgetMultiLangText: visibility.setBundleWidgetMultiLangText,
    ruleMessages: base.ruleMessages,
    ruleMessagesByLocale: display.ruleMessagesByLocale,
    setRuleMessagesByLocale: display.setRuleMessagesByLocale,
    setDiscountMessagingMultiLanguageEnabled:
      display.setDiscountMessagingMultiLanguageEnabled,
    markAsDirty: base.markAsDirty,
  });
  const categoryHandlers = usePpbCategoryHandlers({
    stepsState: base.stepsState,
    markAsDirty: base.markAsDirty,
  });
  const saveHandlers = usePpbSaveHandlers({
    base: {
      allowQuantityChanges: base.allowQuantityChanges,
      bundle: base.bundle,
      bundleProduct: base.bundleProduct,
      cartRedirectToCheckout: base.cartRedirectToCheckout,
      checkAppEmbedStatusBeforePreview: base.checkAppEmbedStatusBeforePreview,
      clearEntitlementFailure: base.clearEntitlementFailure,
      conditionsState: base.conditionsState,
      discardSpecificLinkOfferChanges: base.discardSpecificLinkOfferChanges,
      entitlementFailure: base.entitlementFailure,
      fetcher: base.fetcher,
      formState: base.formState,
      hookHandleDiscard: base.hookHandleDiscard,
      offerDeliveryState: base.offerDeliveryState,
      originalAllowQuantityChangesRef: base.originalAllowQuantityChangesRef,
      originalCartRedirectToCheckoutRef: base.originalCartRedirectToCheckoutRef,
      originalSdkModeRef: base.originalSdkModeRef,
      originalShowProductPricesRef: base.originalShowProductPricesRef,
      originalSubscriptionConfigRef: base.originalSubscriptionConfigRef,
      originalTextOverridesByLocaleRef: base.originalTextOverridesByLocaleRef,
      originalTextOverridesRef: base.originalTextOverridesRef,
      originalValuesRef: base.originalValuesRef,
      pricingState: base.pricingState,
      ruleMessages: base.ruleMessages,
      sdkMode: base.sdkMode,
      selectedCollections: base.selectedCollections,
      setActiveSection: base.setActiveSection,
      setAllowQuantityChanges: base.setAllowQuantityChanges,
      setCartRedirectToCheckout: base.setCartRedirectToCheckout,
      setOperationAlert: base.setOperationAlert,
      setSdkMode: base.setSdkMode,
      setShowProductPrices: base.setShowProductPrices,
      setSubscriptionConfigState: base.setSubscriptionConfigState,
      setTextOverrides: base.setTextOverrides,
      setTextOverridesByLocale: base.setTextOverridesByLocale,
      showProductPrices: base.showProductPrices,
      stepsState: base.stepsState,
      subscriptionConfig: base.subscriptionConfig,
      textOverrides: base.textOverrides,
      textOverridesByLocale: base.textOverridesByLocale,
    },
    visibility: {
      autoSelectBrowsedProduct: visibility.autoSelectBrowsedProduct,
      bundleEmbedAddBrowsedProduct: visibility.bundleEmbedAddBrowsedProduct,
      bundleEmbedCollectionsSelectedData: visibility.bundleEmbedCollectionsSelectedData,
      bundleEmbedDisplayOn: visibility.bundleEmbedDisplayOn,
      bundleEmbedEnabled: visibility.bundleEmbedEnabled,
      bundleEmbedMultiLangText: visibility.bundleEmbedMultiLangText,
      bundleEmbedSelectedProducts: visibility.bundleEmbedSelectedProducts,
      bundleEmbedSpecificCollectionPages: visibility.bundleEmbedSpecificCollectionPages,
      bundleEmbedSpecificProductPages: visibility.bundleEmbedSpecificProductPages,
      bundleEmbedSubTitle: visibility.bundleEmbedSubTitle,
      bundleEmbedTitle: visibility.bundleEmbedTitle,
      bundleWidgetMultiLangText: visibility.bundleWidgetMultiLangText,
      originalAutoSelectBrowsedProductRef: visibility.originalAutoSelectBrowsedProductRef,
      originalBundleEmbedAddBrowsedProductRef: visibility.originalBundleEmbedAddBrowsedProductRef,
      originalBundleEmbedCollectionsSelectedDataRef: visibility.originalBundleEmbedCollectionsSelectedDataRef,
      originalBundleEmbedDisplayOnRef: visibility.originalBundleEmbedDisplayOnRef,
      originalBundleEmbedEnabledRef: visibility.originalBundleEmbedEnabledRef,
      originalBundleEmbedMultiLangTextRef: visibility.originalBundleEmbedMultiLangTextRef,
      originalBundleEmbedSelectedProductsRef: visibility.originalBundleEmbedSelectedProductsRef,
      originalBundleEmbedSpecificCollectionPagesRef: visibility.originalBundleEmbedSpecificCollectionPagesRef,
      originalBundleEmbedSpecificProductPagesRef: visibility.originalBundleEmbedSpecificProductPagesRef,
      originalBundleEmbedSubTitleRef: visibility.originalBundleEmbedSubTitleRef,
      originalBundleEmbedTitleRef: visibility.originalBundleEmbedTitleRef,
      originalUpsellWidgetButtonTextRef: visibility.originalUpsellWidgetButtonTextRef,
      originalUpsellWidgetDescriptionRef: visibility.originalUpsellWidgetDescriptionRef,
      originalUpsellWidgetDisplayModeRef: visibility.originalUpsellWidgetDisplayModeRef,
      originalUpsellWidgetDisplayOnRef: visibility.originalUpsellWidgetDisplayOnRef,
      originalUpsellWidgetEnabledRef: visibility.originalUpsellWidgetEnabledRef,
      originalUpsellWidgetImageUrlRef: visibility.originalUpsellWidgetImageUrlRef,
      originalUpsellWidgetTitleRef: visibility.originalUpsellWidgetTitleRef,
      savedBundleUpsellConfig: visibility.savedBundleUpsellConfig,
      setAutoSelectBrowsedProduct: visibility.setAutoSelectBrowsedProduct,
      setBundleEmbedAddBrowsedProduct: visibility.setBundleEmbedAddBrowsedProduct,
      setBundleEmbedCollectionsSelectedData: visibility.setBundleEmbedCollectionsSelectedData,
      setBundleEmbedDisplayOn: visibility.setBundleEmbedDisplayOn,
      setBundleEmbedEnabled: visibility.setBundleEmbedEnabled,
      setBundleEmbedMultiLangText: visibility.setBundleEmbedMultiLangText,
      setBundleEmbedSelectedProducts: visibility.setBundleEmbedSelectedProducts,
      setBundleEmbedSpecificCollectionPages: visibility.setBundleEmbedSpecificCollectionPages,
      setBundleEmbedSpecificProductPages: visibility.setBundleEmbedSpecificProductPages,
      setBundleEmbedSubTitle: visibility.setBundleEmbedSubTitle,
      setBundleEmbedTitle: visibility.setBundleEmbedTitle,
      setUpsellWidgetButtonText: visibility.setUpsellWidgetButtonText,
      setUpsellWidgetDescription: visibility.setUpsellWidgetDescription,
      setUpsellWidgetDisplayMode: visibility.setUpsellWidgetDisplayMode,
      setUpsellWidgetDisplayOn: visibility.setUpsellWidgetDisplayOn,
      setUpsellWidgetEnabled: visibility.setUpsellWidgetEnabled,
      setUpsellWidgetImageUrl: visibility.setUpsellWidgetImageUrl,
      setUpsellWidgetTitle: visibility.setUpsellWidgetTitle,
      upsellWidgetButtonText: visibility.upsellWidgetButtonText,
      upsellWidgetCollectionsSelectedData: visibility.upsellWidgetCollectionsSelectedData,
      upsellWidgetDescription: visibility.upsellWidgetDescription,
      upsellWidgetDisplayMode: visibility.upsellWidgetDisplayMode,
      upsellWidgetDisplayOn: visibility.upsellWidgetDisplayOn,
      upsellWidgetEnabled: visibility.upsellWidgetEnabled,
      upsellWidgetImageUrl: visibility.upsellWidgetImageUrl,
      upsellWidgetSelectedProducts: visibility.upsellWidgetSelectedProducts,
      upsellWidgetSpecificCollectionPages: visibility.upsellWidgetSpecificCollectionPages,
      upsellWidgetSpecificProductPages: visibility.upsellWidgetSpecificProductPages,
      upsellWidgetTitle: visibility.upsellWidgetTitle,
    },
    display: {
      discountMessagingMultiLanguageEnabled: display.discountMessagingMultiLanguageEnabled,
      globalSuccessMessage: display.globalSuccessMessage,
      progressBarEnabled: display.progressBarEnabled,
      progressBarProgressText: display.progressBarProgressText,
      progressBarSuccessText: display.progressBarSuccessText,
      progressBarType: display.progressBarType,
      qtyOptionsDefaultRuleId: display.qtyOptionsDefaultRuleId,
      qtyOptionsEnabled: display.qtyOptionsEnabled,
      qtyRuleLabels: display.qtyRuleLabels,
      qtyRuleSubtexts: display.qtyRuleSubtexts,
      qtyRuleTextsByLocaleByRuleId: display.qtyRuleTextsByLocaleByRuleId,
      ruleMessagesByLocale: display.ruleMessagesByLocale,
      successMessageByLocale: display.successMessageByLocale,
      tierTextByLocaleByRuleId: display.tierTextByLocaleByRuleId,
      tierTextByRuleId: display.tierTextByRuleId,
    },
    settings: {
      bundleBannerDesktopUrl: settings.bundleBannerDesktopUrl,
      bundleBannerMobileUrl: settings.bundleBannerMobileUrl,
      bundleCartSubtitle: settings.bundleCartSubtitle,
      bundleCartTitle: settings.bundleCartTitle,
      bundleLevelCss: settings.bundleLevelCss,
      countdownEnabled: settings.countdownEnabled,
      countdownExpiredMessage: settings.countdownExpiredMessage,
      countdownExpiryAction: settings.countdownExpiryAction,
      countdownLayout: settings.countdownLayout,
      countdownPosition: settings.countdownPosition,
      countdownTitle: settings.countdownTitle,
      defaultProductsData: settings.defaultProductsData,
      lowStockAlertEnabled: settings.lowStockAlertEnabled,
      lowStockAlertMessage: settings.lowStockAlertMessage,
      lowStockAlertThreshold: settings.lowStockAlertThreshold,
      maxQtyPerProduct: settings.maxQtyPerProduct,
      originalCountdownEnabledRef: settings.originalCountdownEnabledRef,
      originalCountdownExpiredMessageRef: settings.originalCountdownExpiredMessageRef,
      originalCountdownExpiryActionRef: settings.originalCountdownExpiryActionRef,
      originalCountdownLayoutRef: settings.originalCountdownLayoutRef,
      originalCountdownPositionRef: settings.originalCountdownPositionRef,
      originalCountdownTitleRef: settings.originalCountdownTitleRef,
      originalDefaultProductsDataRef: settings.originalDefaultProductsDataRef,
      originalLowStockAlertEnabledRef: settings.originalLowStockAlertEnabledRef,
      originalLowStockAlertMessageRef: settings.originalLowStockAlertMessageRef,
      originalLowStockAlertThresholdRef: settings.originalLowStockAlertThresholdRef,
      originalStickyAddToCartActionRef: settings.originalStickyAddToCartActionRef,
      originalStickyAddToCartEnabledRef: settings.originalStickyAddToCartEnabledRef,
      originalStickyAddToCartShowDesktopRef: settings.originalStickyAddToCartShowDesktopRef,
      originalStickyAddToCartShowMobileRef: settings.originalStickyAddToCartShowMobileRef,
      preSelectedProductVariantId: settings.preSelectedProductVariantId,
      quantityValidationEnabled: settings.quantityValidationEnabled,
      setCountdownEnabled: settings.setCountdownEnabled,
      setCountdownExpiredMessage: settings.setCountdownExpiredMessage,
      setCountdownExpiryAction: settings.setCountdownExpiryAction,
      setCountdownLayout: settings.setCountdownLayout,
      setCountdownPosition: settings.setCountdownPosition,
      setCountdownTitle: settings.setCountdownTitle,
      setDefaultProductsData: settings.setDefaultProductsData,
      setLowStockAlertEnabled: settings.setLowStockAlertEnabled,
      setLowStockAlertMessage: settings.setLowStockAlertMessage,
      setLowStockAlertThreshold: settings.setLowStockAlertThreshold,
      setStickyAddToCartAction: settings.setStickyAddToCartAction,
      setStickyAddToCartEnabled: settings.setStickyAddToCartEnabled,
      setStickyAddToCartShowDesktop: settings.setStickyAddToCartShowDesktop,
      setStickyAddToCartShowMobile: settings.setStickyAddToCartShowMobile,
      showTextOnAddButton: settings.showTextOnAddButton,
      stickyAddToCartAction: settings.stickyAddToCartAction,
      stickyAddToCartEnabled: settings.stickyAddToCartEnabled,
      stickyAddToCartShowDesktop: settings.stickyAddToCartShowDesktop,
      stickyAddToCartShowMobile: settings.stickyAddToCartShowMobile,
      useSingleStepCategoriesAsBundleSteps: settings.useSingleStepCategoriesAsBundleSteps,
      variantSelectorEnabled: settings.variantSelectorEnabled,
    },
    templateState: { setActiveTabIndex: templateState.setActiveTabIndex },
    categoryHandlers: { setCategoryOpen: categoryHandlers.setCategoryOpen },
  });
  const sharedHandlers = useSharedBundleHandlers({
    stepsState: base.stepsState,
    formState: base.formState,
    selectedCollections: base.selectedCollections,
    setSelectedCollections: base.setSelectedCollections,
    setRuleMessages: base.setRuleMessages,
    setBundleProduct: base.setBundleProduct,
    setProductTitle: base.setProductTitle,
    setProductImageUrl: base.setProductImageUrl,
    markAsDirty: base.markAsDirty,
    activeTabIndex: templateState.activeTabIndex,
    setActiveTabIndex: templateState.setActiveTabIndex,
    clearOperationAlert: base.clearOperationAlert,
    shopify: base.shopify,
    fetcher: base.fetcher,
    setIsSyncModalOpen: templateState.setIsSyncModalOpen,
    setSlideDir: templateState.setSlideDir,
    setSlideKey: templateState.setSlideKey,
  });
  usePpbFetcherEffects({
    base: {
      allowQuantityChanges: base.allowQuantityChanges,
      appEmbedEnabled: base.appEmbedEnabled,
      cartRedirectToCheckout: base.cartRedirectToCheckout,
      clearEntitlementFailure: base.clearEntitlementFailure,
      clearOperationAlert: base.clearOperationAlert,
      fetcher: base.fetcher,
      lastProcessedFetcherDataRef: base.lastProcessedFetcherDataRef,
      markAsSaved: base.markAsSaved,
      markSpecificLinkOfferSaved: base.markSpecificLinkOfferSaved,
      openPageSelectionModal: base.openPageSelectionModal,
      originalAllowQuantityChangesRef: base.originalAllowQuantityChangesRef,
      originalCartRedirectToCheckoutRef: base.originalCartRedirectToCheckoutRef,
      originalSdkModeRef: base.originalSdkModeRef,
      originalShowProductPricesRef: base.originalShowProductPricesRef,
      originalSubscriptionConfigRef: base.originalSubscriptionConfigRef,
      originalTextOverridesByLocaleRef: base.originalTextOverridesByLocaleRef,
      originalTextOverridesRef: base.originalTextOverridesRef,
      revalidator: base.revalidator,
      sdkMode: base.sdkMode,
      setAvailablePages: base.setAvailablePages,
      setEntitlementFailure: base.setEntitlementFailure,
      setIsLoadingPages: base.setIsLoadingPages,
      setOperationAlert: base.setOperationAlert,
      shopify: base.shopify,
      showProductPrices: base.showProductPrices,
      subscriptionConfig: base.subscriptionConfig,
      textOverrides: base.textOverrides,
      textOverridesByLocale: base.textOverridesByLocale,
    },
    visibility: {
      autoSelectBrowsedProduct: visibility.autoSelectBrowsedProduct,
      bundleEmbedAddBrowsedProduct: visibility.bundleEmbedAddBrowsedProduct,
      bundleEmbedCollectionsSelectedData: visibility.bundleEmbedCollectionsSelectedData,
      bundleEmbedDisplayOn: visibility.bundleEmbedDisplayOn,
      bundleEmbedEnabled: visibility.bundleEmbedEnabled,
      bundleEmbedMultiLangText: visibility.bundleEmbedMultiLangText,
      bundleEmbedSelectedProducts: visibility.bundleEmbedSelectedProducts,
      bundleEmbedSpecificCollectionPages: visibility.bundleEmbedSpecificCollectionPages,
      bundleEmbedSpecificProductPages: visibility.bundleEmbedSpecificProductPages,
      bundleEmbedSubTitle: visibility.bundleEmbedSubTitle,
      bundleEmbedTitle: visibility.bundleEmbedTitle,
      originalAutoSelectBrowsedProductRef: visibility.originalAutoSelectBrowsedProductRef,
      originalBundleEmbedAddBrowsedProductRef: visibility.originalBundleEmbedAddBrowsedProductRef,
      originalBundleEmbedCollectionsSelectedDataRef: visibility.originalBundleEmbedCollectionsSelectedDataRef,
      originalBundleEmbedDisplayOnRef: visibility.originalBundleEmbedDisplayOnRef,
      originalBundleEmbedEnabledRef: visibility.originalBundleEmbedEnabledRef,
      originalBundleEmbedMultiLangTextRef: visibility.originalBundleEmbedMultiLangTextRef,
      originalBundleEmbedSelectedProductsRef: visibility.originalBundleEmbedSelectedProductsRef,
      originalBundleEmbedSpecificCollectionPagesRef: visibility.originalBundleEmbedSpecificCollectionPagesRef,
      originalBundleEmbedSpecificProductPagesRef: visibility.originalBundleEmbedSpecificProductPagesRef,
      originalBundleEmbedSubTitleRef: visibility.originalBundleEmbedSubTitleRef,
      originalBundleEmbedTitleRef: visibility.originalBundleEmbedTitleRef,
      originalUpsellWidgetButtonTextRef: visibility.originalUpsellWidgetButtonTextRef,
      originalUpsellWidgetDescriptionRef: visibility.originalUpsellWidgetDescriptionRef,
      originalUpsellWidgetDisplayModeRef: visibility.originalUpsellWidgetDisplayModeRef,
      originalUpsellWidgetDisplayOnRef: visibility.originalUpsellWidgetDisplayOnRef,
      originalUpsellWidgetEnabledRef: visibility.originalUpsellWidgetEnabledRef,
      originalUpsellWidgetImageUrlRef: visibility.originalUpsellWidgetImageUrlRef,
      originalUpsellWidgetTitleRef: visibility.originalUpsellWidgetTitleRef,
      upsellWidgetButtonText: visibility.upsellWidgetButtonText,
      upsellWidgetDescription: visibility.upsellWidgetDescription,
      upsellWidgetDisplayMode: visibility.upsellWidgetDisplayMode,
      upsellWidgetDisplayOn: visibility.upsellWidgetDisplayOn,
      upsellWidgetEnabled: visibility.upsellWidgetEnabled,
      upsellWidgetImageUrl: visibility.upsellWidgetImageUrl,
      upsellWidgetTitle: visibility.upsellWidgetTitle,
    },
    settings: {
      countdownEnabled: settings.countdownEnabled,
      countdownExpiredMessage: settings.countdownExpiredMessage,
      countdownExpiryAction: settings.countdownExpiryAction,
      countdownLayout: settings.countdownLayout,
      countdownPosition: settings.countdownPosition,
      countdownTitle: settings.countdownTitle,
      defaultProductsData: settings.defaultProductsData,
      lowStockAlertEnabled: settings.lowStockAlertEnabled,
      lowStockAlertMessage: settings.lowStockAlertMessage,
      lowStockAlertThreshold: settings.lowStockAlertThreshold,
      originalCountdownEnabledRef: settings.originalCountdownEnabledRef,
      originalCountdownExpiredMessageRef: settings.originalCountdownExpiredMessageRef,
      originalCountdownExpiryActionRef: settings.originalCountdownExpiryActionRef,
      originalCountdownLayoutRef: settings.originalCountdownLayoutRef,
      originalCountdownPositionRef: settings.originalCountdownPositionRef,
      originalCountdownTitleRef: settings.originalCountdownTitleRef,
      originalDefaultProductsDataRef: settings.originalDefaultProductsDataRef,
      originalLowStockAlertEnabledRef: settings.originalLowStockAlertEnabledRef,
      originalLowStockAlertMessageRef: settings.originalLowStockAlertMessageRef,
      originalLowStockAlertThresholdRef: settings.originalLowStockAlertThresholdRef,
      originalStickyAddToCartActionRef: settings.originalStickyAddToCartActionRef,
      originalStickyAddToCartEnabledRef: settings.originalStickyAddToCartEnabledRef,
      originalStickyAddToCartShowDesktopRef: settings.originalStickyAddToCartShowDesktopRef,
      originalStickyAddToCartShowMobileRef: settings.originalStickyAddToCartShowMobileRef,
      stickyAddToCartAction: settings.stickyAddToCartAction,
      stickyAddToCartEnabled: settings.stickyAddToCartEnabled,
      stickyAddToCartShowDesktop: settings.stickyAddToCartShowDesktop,
      stickyAddToCartShowMobile: settings.stickyAddToCartShowMobile,
    },
    templateState: {
      lastTemplateRequestRef: templateState.lastTemplateRequestRef,
      lastTemplateResponseRef: templateState.lastTemplateResponseRef,
      pendingPlacementModalRef: templateState.pendingPlacementModalRef,
      setBundleDesignPresetId: templateState.setBundleDesignPresetId,
      setBundleDesignTemplate: templateState.setBundleDesignTemplate,
      setIsPreparingPlacementTemplates: templateState.setIsPreparingPlacementTemplates,
      setTemplateModalStep: templateState.setTemplateModalStep,
      setTemplateSaveError: templateState.setTemplateSaveError,
      setTemplateSyncRequired: templateState.setTemplateSyncRequired,
      templateFetcher: templateState.templateFetcher,
      templateSubmissionStartedRef: templateState.templateSubmissionStartedRef,
      setIsSelectTemplateModalOpen: templateState.setIsSelectTemplateModalOpen,
    },
    sharedHandlers: {
      enhanceTemplateListWithUserSelection: sharedHandlers.enhanceTemplateListWithUserSelection,
    },
    saveHandlers: {
      clearValidationErrors: saveHandlers.clearValidationErrors,
      setServerFieldErrors: saveHandlers.setServerFieldErrors,
    },
  });
  const handleAddToStorefront = useCallback(() => {
    base.clearOperationAlert();
    base.openThemeEditorForAppEmbed();
  }, [base]);
  const previewReadiness = usePpbPreviewReadinessHandlers({
    base: {
      apiKey: base.apiKey,
      appEmbedEnabled: base.appEmbedEnabled,
      blockHandle: base.blockHandle,
      bundle: base.bundle,
      bundleProduct: base.bundleProduct,
      clearOperationAlert: base.clearOperationAlert,
      forceNavigation: base.forceNavigation,
      formState: base.formState,
      isDirty: base.isDirty,
      loadedBundleProduct: base.loadedBundleProduct,
      loaderData: base.loaderData,
      navigate: base.navigate,
      openThemeEditorForAppEmbed: base.openThemeEditorForAppEmbed,
      pricingState: base.pricingState,
      productStatus: base.productStatus,
      refreshParentProductStatusFromShopify: base.refreshParentProductStatusFromShopify,
      setActiveSection: base.setActiveSection,
      setOperationAlert: base.setOperationAlert,
      shop: base.shop,
      shopify: base.shopify,
      stepsState: base.stepsState,
      themeEditorUrl: base.themeEditorUrl,
      triggerSaveBarIrritation: base.triggerSaveBarIrritation,
    },
    visibility: {
      bundleEmbedEnabled: visibility.bundleEmbedEnabled,
      upsellWidgetEnabled: visibility.upsellWidgetEnabled,
    },
    templateState: {
      hasPreview: templateState.hasPreview,
      setActiveTabIndex: templateState.setActiveTabIndex,
      setHasPreview: templateState.setHasPreview,
      setReadinessOpen: templateState.setReadinessOpen,
      setSlideDir: templateState.setSlideDir,
      setSlideKey: templateState.setSlideKey,
    },
  });
  const placement = usePpbPlacementHandlers({
    base: {
      activeSection: base.activeSection,
      apiKey: base.apiKey,
      blockHandle: base.blockHandle,
      bundle: base.bundle,
      bundleProduct: base.bundleProduct,
      clearOperationAlert: base.clearOperationAlert,
      closeCollectionsModal: base.closeCollectionsModal,
      closePageSelectionModal: base.closePageSelectionModal,
      closeProductsModal: base.closeProductsModal,
      fetcher: base.fetcher,
      markAsDirty: base.markAsDirty,
      setCurrentModalStepId: base.setCurrentModalStepId,
      setIsLoadingPages: base.setIsLoadingPages,
      setOperationAlert: base.setOperationAlert,
      setSelectedPage: base.setSelectedPage,
      shop: base.shop,
      shopify: base.shopify,
    },
    visibility: {
      bundleEmbedCollectionsSelectedData: visibility.bundleEmbedCollectionsSelectedData,
      bundleEmbedSelectedProducts: visibility.bundleEmbedSelectedProducts,
      setBundleEmbedCollectionsSelectedData: visibility.setBundleEmbedCollectionsSelectedData,
      setBundleEmbedSelectedProducts: visibility.setBundleEmbedSelectedProducts,
      setBundleEmbedSpecificCollectionPages: visibility.setBundleEmbedSpecificCollectionPages,
      setBundleEmbedSpecificProductPages: visibility.setBundleEmbedSpecificProductPages,
      setUpsellWidgetCollectionsSelectedData: visibility.setUpsellWidgetCollectionsSelectedData,
      setUpsellWidgetSelectedProducts: visibility.setUpsellWidgetSelectedProducts,
      setUpsellWidgetSpecificCollectionPages: visibility.setUpsellWidgetSpecificCollectionPages,
      setUpsellWidgetSpecificProductPages: visibility.setUpsellWidgetSpecificProductPages,
      upsellWidgetCollectionsSelectedData: visibility.upsellWidgetCollectionsSelectedData,
      upsellWidgetSelectedProducts: visibility.upsellWidgetSelectedProducts,
    },
    templateState: {
      pendingPlacementModalRef: templateState.pendingPlacementModalRef,
      setIsPreparingPlacementTemplates: templateState.setIsPreparingPlacementTemplates,
    },
  });
  const modalAndTemplate = usePpbModalAndTemplateController({
    base: {
      appEmbedEnabled: base.appEmbedEnabled,
      isCollectionsModalOpen: base.isCollectionsModalOpen,
      isProductsModalOpen: base.isProductsModalOpen,
      navigate: base.navigate,
      shopify: base.shopify,
      setEntitlementFailure: base.setEntitlementFailure,
      isFreePlan: base.isFreePlan,
    },
    display: {
      discountVariablesModalRef: display.discountVariablesModalRef,
      isDiscountVariablesModalOpen: display.isDiscountVariablesModalOpen,
      setIsDiscountVariablesModalOpen: display.setIsDiscountVariablesModalOpen,
    },
    templateState: {
      bundleDesignPresetId: templateState.bundleDesignPresetId,
      bundleDesignTemplate: templateState.bundleDesignTemplate,
      isSyncModalOpen: templateState.isSyncModalOpen,
      lastTemplateRequestRef: templateState.lastTemplateRequestRef,
      lastTemplateResponseRef: templateState.lastTemplateResponseRef,
      pendingDesignPresetId: templateState.pendingDesignPresetId,
      pendingDesignTemplate: templateState.pendingDesignTemplate,
      selectTemplateOpenButtonRef: templateState.selectTemplateOpenButtonRef,
      setIsSelectTemplateModalOpen: templateState.setIsSelectTemplateModalOpen,
      setIsSyncModalOpen: templateState.setIsSyncModalOpen,
      setPendingDesignPresetId: templateState.setPendingDesignPresetId,
      setPendingDesignTemplate: templateState.setPendingDesignTemplate,
      setTemplateModalStep: templateState.setTemplateModalStep,
      setTemplateSaveError: templateState.setTemplateSaveError,
      setTemplateSyncRequired: templateState.setTemplateSyncRequired,
      templateFetcher: templateState.templateFetcher,
      templateSubmissionStartedRef: templateState.templateSubmissionStartedRef,
    },
    placement: {
      handleCloseCollectionsModal: placement.handleCloseCollectionsModal,
      handleCloseProductsModal: placement.handleCloseProductsModal,
    },
    previewReadiness: {
      handlePreviewBundle: previewReadiness.handlePreviewBundle,
    },
    saveHandlers: { handleDiscard: saveHandlers.handleDiscard },
  });

  return {
    ...base,
    ...visibility,
    ...display,
    ...settings,
    ...templateState,
    ...multiLanguage,
    ...categoryHandlers,
    ...saveHandlers,
    ...sharedHandlers,
    handleAddToStorefront,
    ...previewReadiness,
    ...placement,
    ...modalAndTemplate,
  };
}

export type PpbConfigureFlow = ReturnType<typeof usePpbConfigureFlow>;
