api_version = "2026-04"

[[extensions]]
name = "t:name"
handle = "bundle-discount-function"
type = "function"
uid = "b476b856-705c-eaa2-17d5-8a972268feb0e7bf1010"
description = "t:description"

  [[extensions.targeting]]
  target = "cart.lines.discounts.generate.run"
  input_query = "src/cart_lines_discounts_generate_run.graphql"
  export = "cart_lines_discounts_generate_run"

  [extensions.build]
  command = "node ../../scripts/build-discount-function.mjs"
  path = "target/wasm32-unknown-unknown/release/bundle-discount-function.wasm"
  watch = ["src/**/*.rs", "src/**/*.graphql", "Cargo.toml", "Cargo.lock", "../bundle-runtime-policy/src/**/*.rs", "../bundle-runtime-policy/Cargo.toml", "../../scripts/build-discount-function.mjs"]

  [extensions.input.variables]
  namespace = "$app"
  key = "discount_configuration"
