query Input {
  presentmentCurrencyRate
  localization { country { isoCode } }
  shop {
    ppbPolicyRevisions: metafield(namespace: "$app", key: "ppb_policy_revisions") { value: jsonValue }
  }
  cartTransform {
    runtimeConfiguration: metafield(namespace: "$app", key: "runtime_configuration") {
      value: jsonValue
    }
  }
  cart {
    lines {
      id
      quantity
      bundleDisplayProperties: attribute(key: "_bundle_display_properties") { value }
      stepType: attribute(key: "_bundle_step_type") {
        value
      }
      selection: attribute(key: "_wpb_selection") { value }
      sellingPlanAllocation { __typename }
      merchandise {
        __typename
        ... on ProductVariant {
          id
          weight
          weightUnit
          product {
            id
            runtimePolicies: metafield(namespace: "$app", key: "bundle_runtime_memberships") {
              value: jsonValue
            }
          }

        }
      }
      cost {
        amountPerQuantity {
          amount
          currencyCode
        }
      }
    }
  }
}
