/// Domain types for bundle cart transform.
///
/// These are JSON-deserialized from Shopify metafield values — NOT generated
/// by #[typegen]. typegen handles the cart input + operation output schema;
/// these types handle the business-logic JSON payloads stored in metafields.
///
/// OUTPUT structs (FunctionRunResult, CartOperation, MergeOperation, etc.)
/// come from crate::schema (generated by #[typegen]) and implement
/// shopify_function_wasm_api::Serialize. Do NOT redefine them here.

// ============================================================================
// METAFIELD JSON TYPES — deserialized from metafield string values
// ============================================================================

/// Parent identity and pricing resolved from the published policy.
#[derive(serde::Deserialize)]
#[cfg_attr(test, derive(Debug))]
pub struct ComponentParent {
    /// Parent variant GID, e.g. "gid://shopify/ProductVariant/123"
    pub id: String,
    #[serde(default)]
    pub price_adjustment: Option<PriceAdjustmentConfig>,
}

/// Deserialized from `$app:price_adjustment` metafield.
/// Also embedded inside `ComponentParent.price_adjustment`.
pub use bundle_runtime_policy::pricing::{PriceAdjustmentConfig, PricingMethod, ConditionType};

#[derive(Clone)]
#[cfg_attr(test, derive(Debug))]
pub struct CartLineMessagingSettings {
    pub is_enabled: bool,
    pub show_original_price: bool,
    pub discount_display: CartLineDiscountDisplaySettings,
}

impl Default for CartLineMessagingSettings {
    fn default() -> Self {
        Self {
            is_enabled: true,
            show_original_price: true,
            discount_display: CartLineDiscountDisplaySettings::default(),
        }
    }
}

#[derive(Clone)]
#[cfg_attr(test, derive(Debug))]
pub struct CartLineDiscountDisplaySettings {
    pub is_enabled: bool,
}

#[derive(Clone, Default)]
#[cfg_attr(test, derive(Debug))]
pub struct CartTransformRuntimeConfiguration {
    pub bundle_cart_line_messaging: CartLineMessagingSettings,
}

impl CartTransformRuntimeConfiguration {
    pub fn from_value(value: Option<&shopify_function::wasm_api::Value>) -> Self {
        let Some(value) = value else {
            return Self::default();
        };
        let messaging = value.get_obj_prop("bundleCartLineMessaging");
        let discount = messaging.get_obj_prop("discountDisplay");
        Self {
            bundle_cart_line_messaging: CartLineMessagingSettings {
                is_enabled: messaging
                    .get_obj_prop("isEnabled")
                    .as_bool()
                    .unwrap_or(true),
                show_original_price: messaging
                    .get_obj_prop("showOriginalPrice")
                    .as_bool()
                    .unwrap_or(true),
                discount_display: CartLineDiscountDisplaySettings {
                    is_enabled: discount.get_obj_prop("isEnabled").as_bool().unwrap_or(true),
                },
            },
        }
    }
}

impl Default for CartLineDiscountDisplaySettings {
    fn default() -> Self {
        Self {
            is_enabled: true,
        }
    }
}

#[derive(serde::Deserialize, Clone, Default)]
#[cfg_attr(test, derive(Debug))]
#[serde(rename_all = "camelCase")]
pub struct CartLineDisplayProperties {
    #[serde(default)]
    pub offer_analytics: Option<CartLineOfferAnalytics>,
    #[serde(default, alias = "tier_progress")]
    pub tier_progress: Option<Box<serde_json::value::RawValue>>,
}

#[derive(serde::Deserialize, serde::Serialize, Clone, Default)]
#[cfg_attr(test, derive(Debug))]
#[serde(rename_all = "camelCase")]
pub struct CartLineOfferAnalytics {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub bundle_id: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub offer_policy_id: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub offer_rule_version: Option<i64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub offer_tier_id: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub offer_eligibility_source: Option<String>,
}
