query Input($windowStart: TimeWithoutTimezone!, $windowEnd: TimeWithoutTimezone!) {
  presentmentCurrencyRate
  localization { country { isoCode } }
  shop {
    ppbPolicyRevisions: metafield(namespace: "$app", key: "ppb_policy_revisions") { value: jsonValue }
    localTime { date afterStart: timeAfter(time: $windowStart) beforeEnd: timeBefore(time: $windowEnd) }
  }
  cart {
    lines {
      id
      quantity
      selection: attribute(key: "_wpb_selection") { value }
      sellingPlanAllocation { sellingPlan { id } }
      merchandise {
        __typename
        ... on ProductVariant {
          id
          weight
          weightUnit
          product {
            id
            runtimePolicies: metafield(namespace: "$app", key: "bundle_runtime_memberships") { value: jsonValue }
          }
        }
      }
      cost { amountPerQuantity { amount } }
    }
  }
  discount {
    discountClasses
    configuration: metafield(namespace: "$app", key: "discount_configuration") { value: jsonValue }
  }
  triggeringDiscountCode
}
