# Learn more about configuring your checkout UI extension:
# https://shopify.dev/docs/api/checkout-ui-extensions/latest/configuration

# The version of APIs your extension will receive. Learn more:
# https://shopify.dev/docs/api/usage/versioning
api_version = "2026-07"

[[extensions]]
uid = "feb2dedd-7b8a-5fa3-1766-e04fa7aebc8abbe9ecbf"
type = "ui_extension"
name = "Bundle Pricing - Checkout"
handle = "bundle-checkout-ui"

  [[extensions.targeting]]
  module = "./src/BundleOffers.tsx"
  target = "purchase.checkout.block.render"
  default_placement = "ORDER_SUMMARY2"

  [[extensions.targeting]]
  module = "./src/TotalSavings.tsx"
  target = "purchase.checkout.reductions.render-after"

  [extensions.capabilities]
  api_access = true

  [[extensions.metafields]]
  namespace = "$app"
  key = "bundle_ui_config"

  [[extensions.metafields]]
  namespace = "$app"
  key = "bundle_runtime_policies"
